# Generated by Django 6.0.2 on 2026-02-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='project/images/')),
                ('project_name', models.CharField(max_length=100)),
                ('project_about', models.TextField()),
                ('technology', models.CharField(max_length=200)),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
            ],
        ),
    ]
