# Generated by Django 6.0.2 on 2026-02-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_avatar_url', models.URLField()),
                ('member_name', models.CharField(max_length=100)),
                ('member_post', models.CharField(max_length=100)),
                ('about_member', models.CharField(max_length=200)),
                ('linkedin_url', models.URLField()),
                ('github_url', models.URLField()),
            ],
        ),
    ]
