# Generated by Django 6.0.4 on 2026-08-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
